export const TransactionConstants = {
  GET_TRANSACTION_REQUEST: "GET_TRANSACTION_REQUEST",
  GET_TRANSACTION_SUCCESS: "GET_TRANSACTION_SUCCESS",
  GET_TRANSACTION_FAILED: "GET_TRANSACTION_FAILED",

  CREATE_TRANSACTION_REQUEST: "CREATE_TRANSACTION_REQUEST",
  CREATE_TRANSACTION_SUCCESS: "CREATE_TRANSACTION_SUCCESS",
  CREATE_TRANSACTION_FAILED: "CREATE_TRANSACTION_FAILED",
};
